/* The following code was generated by JFlex 1.7.0 */

package compiler;

import java.util.*;
import java.io.IOException;
import compiler.exceptions.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/compiler/Scanner.flex</tt>
 */
class Scanner {

  /** This character denotes the end of file */
  private static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  private static final int YYINITIAL = 0;
  private static final int COMMENT_STATE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\6\1\10\1\10\1\7\22\0\1\12\1\41\6\0"+
    "\1\37\1\40\1\11\1\34\1\0\1\33\1\0\1\5\1\3\11\4"+
    "\1\35\1\0\1\43\1\36\1\42\2\0\1\32\1\13\1\1\1\23"+
    "\1\14\1\24\1\15\1\26\1\16\2\1\1\27\1\1\1\17\1\22"+
    "\1\20\1\1\1\21\1\30\1\25\2\1\1\31\3\1\6\0\32\2"+
    "\12\0\1\10\u1fa2\0\1\10\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\2\3\1\4\2\5\1\6\1\7"+
    "\10\1\1\10\1\11\1\1\1\12\1\13\1\14\1\1"+
    "\1\15\1\16\2\7\1\0\1\17\1\7\1\20\1\21"+
    "\3\0\1\22\2\0\1\23\2\0\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\13\0\1\32\1\0\1\33\1\34"+
    "\2\0\1\35\2\0\1\36\1\37\4\0\1\40\2\0"+
    "\1\41\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\110\0\264\0\330"+
    "\0\110\0\374\0\u0120\0\110\0\u0144\0\u0168\0\u018c\0\u01b0"+
    "\0\u01d4\0\u01f8\0\u021c\0\u0240\0\110\0\110\0\u0264\0\110"+
    "\0\110\0\110\0\u0288\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\154"+
    "\0\u033c\0\u0360\0\110\0\110\0\u0384\0\u03a8\0\u03cc\0\154"+
    "\0\u03f0\0\u0414\0\154\0\u0438\0\u045c\0\110\0\110\0\110"+
    "\0\110\0\110\0\110\0\u0480\0\u04a4\0\u04c8\0\u04ec\0\u0510"+
    "\0\u0534\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\154\0\u060c"+
    "\0\154\0\154\0\u0630\0\u0654\0\154\0\u0678\0\u069c\0\154"+
    "\0\154\0\u06c0\0\u06e4\0\u0708\0\u072c\0\154\0\u0750\0\u0774"+
    "\0\154\0\154";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\3\1\13\1\14\1\15\1\16\1\4\1\17\1\4"+
    "\1\20\1\21\1\4\1\22\1\4\1\23\3\4\1\24"+
    "\1\4\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\5\14\1\36\3\14\1\37\32\14\45\0"+
    "\1\40\3\41\6\0\20\40\13\0\3\5\42\0\2\7"+
    "\44\0\1\42\3\0\1\43\40\0\1\11\42\0\1\44"+
    "\37\0\1\40\3\41\6\0\1\40\1\45\16\40\12\0"+
    "\1\40\3\41\6\0\4\40\1\46\7\40\1\47\3\40"+
    "\12\0\1\40\3\41\6\0\11\40\1\50\6\40\12\0"+
    "\1\40\3\41\6\0\6\40\1\51\11\40\12\0\1\40"+
    "\3\41\6\0\1\40\1\52\16\40\12\0\1\40\3\41"+
    "\6\0\7\40\1\53\10\40\12\0\1\40\3\41\6\0"+
    "\13\40\1\54\4\40\12\0\1\40\3\41\6\0\13\40"+
    "\1\55\4\40\47\0\1\56\43\0\1\57\43\0\1\60"+
    "\43\0\1\61\16\0\1\62\37\0\1\63\37\0\4\41"+
    "\6\0\20\41\11\0\6\42\3\0\33\42\1\0\1\40"+
    "\3\41\6\0\2\40\1\64\15\40\12\0\1\40\3\41"+
    "\6\0\10\40\1\65\7\40\12\0\1\40\3\41\6\0"+
    "\15\40\1\66\2\40\12\0\1\40\3\41\6\0\3\40"+
    "\1\67\14\40\12\0\1\40\3\41\6\0\17\40\1\70"+
    "\12\0\1\40\3\41\6\0\1\40\1\71\16\40\12\0"+
    "\1\40\3\41\6\0\3\40\1\72\14\40\12\0\1\40"+
    "\3\41\6\0\3\40\1\73\14\40\12\0\1\40\3\41"+
    "\6\0\3\40\1\74\1\40\1\75\10\40\1\76\1\40"+
    "\12\0\1\40\3\41\6\0\1\40\1\77\16\40\12\0"+
    "\1\40\3\41\6\0\4\40\1\100\13\40\12\0\1\40"+
    "\3\41\6\0\10\40\1\101\7\40\12\0\1\40\3\41"+
    "\6\0\4\40\1\102\13\40\12\0\1\40\3\41\6\0"+
    "\14\40\1\103\3\40\12\0\1\40\3\41\6\0\4\40"+
    "\1\104\13\40\12\0\1\40\3\41\6\0\11\40\1\105"+
    "\6\40\12\0\1\40\3\41\6\0\6\40\1\106\11\40"+
    "\12\0\1\40\3\41\6\0\13\40\1\107\4\40\12\0"+
    "\1\40\3\41\6\0\12\40\1\110\5\40\12\0\1\40"+
    "\3\41\6\0\1\40\1\111\16\40\12\0\1\40\3\41"+
    "\6\0\5\40\1\112\12\40\12\0\1\40\3\41\6\0"+
    "\7\40\1\113\10\40\12\0\1\40\3\41\6\0\3\40"+
    "\1\114\14\40\12\0\1\40\3\41\6\0\6\40\1\115"+
    "\11\40\12\0\1\40\3\41\6\0\2\40\1\116\15\40"+
    "\12\0\1\40\3\41\6\0\14\40\1\117\3\40\12\0"+
    "\1\40\3\41\6\0\7\40\1\120\10\40\12\0\1\40"+
    "\3\41\6\0\1\40\1\121\16\40\12\0\1\40\3\41"+
    "\6\0\2\40\1\122\15\40\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1944];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\2\1\1\11\2\1\1\11\2\1\1\11"+
    "\10\1\2\11\1\1\3\11\5\1\1\0\2\1\2\11"+
    "\3\0\1\1\2\0\1\1\2\0\6\11\13\0\1\1"+
    "\1\0\2\1\2\0\1\1\2\0\2\1\4\0\1\1"+
    "\2\0\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private int nestedCommentCounter = 0;
    /**
     * Run the scanning process.
     *
     * @return The list of tokens that the code contains
     * @throws LexicalException When a lexical problem is encountered
     * @throws SyntaxException When a syntax problem is encountered
     * @throws IOException When another problem is encountered
     */
    public List<Symbol> scan() throws LexicalException, SyntaxException, IOException {
        List<Symbol> tokens = new ArrayList<>();
        Symbol currentSymbol = nextToken();
        while ((currentSymbol == null) || currentSymbol.getType() != LexicalUnit.EOS) {
            if (currentSymbol != null) {
                tokens.add(currentSymbol);
            }
            currentSymbol = nextToken();
        }
        return tokens;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  private final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  private final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  private final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  private final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  private final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  private final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  private final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private Symbol nextToken() throws java.io.IOException, LexicalException, SyntaxException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     if(yystate() == COMMENT_STATE) {
        throw new SyntaxException("Comment not closed");
    } else {
        return new compiler.Symbol(LexicalUnit.EOS, yyline, yycolumn);
    }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new LexicalException("Syntax error at line " + yyline + " column " + yycolumn);
            } 
            // fall through
          case 35: break;
          case 2: 
            { return new Symbol(LexicalUnit.VARNAME,yyline, yycolumn, yytext());
            } 
            // fall through
          case 36: break;
          case 3: 
            { return new Symbol(LexicalUnit.NUMBER,yyline, yycolumn, yytext());
            } 
            // fall through
          case 37: break;
          case 4: 
            { return new Symbol(LexicalUnit.DIVIDE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 38: break;
          case 5: 
            { return new Symbol(LexicalUnit.ENDLINE,yyline, yycolumn, "\\n");
            } 
            // fall through
          case 39: break;
          case 6: 
            { return new Symbol(LexicalUnit.TIMES,yyline, yycolumn, yytext());
            } 
            // fall through
          case 40: break;
          case 7: 
            { 
            } 
            // fall through
          case 41: break;
          case 8: 
            { return new Symbol(LexicalUnit.MINUS,yyline, yycolumn, yytext());
            } 
            // fall through
          case 42: break;
          case 9: 
            { return new Symbol(LexicalUnit.PLUS,yyline, yycolumn, yytext());
            } 
            // fall through
          case 43: break;
          case 10: 
            { return new Symbol(LexicalUnit.EQ,yyline, yycolumn, yytext());
            } 
            // fall through
          case 44: break;
          case 11: 
            { return new Symbol(LexicalUnit.LPAREN,yyline, yycolumn, yytext());
            } 
            // fall through
          case 45: break;
          case 12: 
            { return new Symbol(LexicalUnit.RPAREN,yyline, yycolumn, yytext());
            } 
            // fall through
          case 46: break;
          case 13: 
            { return new Symbol(LexicalUnit.GT,yyline, yycolumn, yytext());
            } 
            // fall through
          case 47: break;
          case 14: 
            { return new Symbol(LexicalUnit.LT,yyline, yycolumn, yytext());
            } 
            // fall through
          case 48: break;
          case 15: 
            { return new Symbol(LexicalUnit.PROGNAME,yyline, yycolumn, yytext());
            } 
            // fall through
          case 49: break;
          case 16: 
            { nestedCommentCounter++; yybegin(COMMENT_STATE);
            } 
            // fall through
          case 50: break;
          case 17: 
            { throw new SyntaxException("Closing without opening comment at line " + yyline + " column " + yycolumn);
            } 
            // fall through
          case 51: break;
          case 18: 
            { return new Symbol(LexicalUnit.IF,yyline, yycolumn, yytext());
            } 
            // fall through
          case 52: break;
          case 19: 
            { return new Symbol(LexicalUnit.DO,yyline, yycolumn, yytext());
            } 
            // fall through
          case 53: break;
          case 20: 
            { return new Symbol(LexicalUnit.ASSIGN,yyline, yycolumn, yytext());
            } 
            // fall through
          case 54: break;
          case 21: 
            { return new Symbol(LexicalUnit.NEQ,yyline, yycolumn, yytext());
            } 
            // fall through
          case 55: break;
          case 22: 
            { return new Symbol(LexicalUnit.GTE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 56: break;
          case 23: 
            { return new Symbol(LexicalUnit.LTE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 57: break;
          case 24: 
            { nestedCommentCounter++;
            } 
            // fall through
          case 58: break;
          case 25: 
            { nestedCommentCounter--;
                        if(nestedCommentCounter == 0) {yybegin(YYINITIAL);}
            } 
            // fall through
          case 59: break;
          case 26: 
            { return new Symbol(LexicalUnit.ELSE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 60: break;
          case 27: 
            { return new Symbol(LexicalUnit.READ,yyline, yycolumn, yytext());
            } 
            // fall through
          case 61: break;
          case 28: 
            { return new Symbol(LexicalUnit.THEN,yyline, yycolumn, yytext());
            } 
            // fall through
          case 62: break;
          case 29: 
            { return new Symbol(LexicalUnit.ENDIF,yyline, yycolumn, yytext());
            } 
            // fall through
          case 63: break;
          case 30: 
            { return new Symbol(LexicalUnit.PRINT,yyline, yycolumn, yytext());
            } 
            // fall through
          case 64: break;
          case 31: 
            { return new Symbol(LexicalUnit.WHILE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 65: break;
          case 32: 
            { return new Symbol(LexicalUnit.ENDPROG,yyline, yycolumn, yytext());
            } 
            // fall through
          case 66: break;
          case 33: 
            { return new Symbol(LexicalUnit.ENDWHILE,yyline, yycolumn, yytext());
            } 
            // fall through
          case 67: break;
          case 34: 
            { return new Symbol(LexicalUnit.BEGINPROG,yyline, yycolumn, yytext());
            } 
            // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
